### ISSUE TITLE
Consolidate development mode NPM scripts

### ISSUE THREAD

**Issue by greatislander** [sachin10101998/fluidic-11ty#2]
## Is your feature request related to a problem?

Currently there are two scripts in `package.json`, `eleventy` and `eleventyport`, both of which run 11ty in `--serve` mode with the default port (`npm run eleventy`) and the default port for DocPad (`npm run eleventyport`).

## Describe the solution you'd like

I'd suggest replacing these with a single script, `start`:

```js
"start": "eleventy --serve"
```

The custom port is not necessary for maintaining backwards compatibility with DocPad as this is meant to be a starter kit, and using the `start` script means a developer can start the project by executing `npm start` instead of `npm run <scriptname>` which is a small but meaningful improvement in development experience.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

NPM docs: https://docs.npmjs.com/cli/start.html

**Comment by sachin10101998** [comment]
Thanks @greatislander . I have added the required scripts for starting the server, building, linting, cleaning output directories, etc.. Let me know if you need further modifications to the scripts. If not, we can close this issue.

**Comment by greatislander** [comment]
Hi @sachin10101998, I left a comment on your commit. Also you'll need to update the README as it still references the `eleventyport` script. Looks good otherwise.

**Comment by sachin10101998** [comment]
@greatislander  I made the suggested changes.

**Comment by greatislander** [comment]
Fixed in https://github.com/sachin10101998/fluidic-11ty/commit/46b7f100b91758c17918a647d6d4a423b7106240 and https://github.com/sachin10101998/fluidic-11ty/commit/12b5bd9325a11ae4c9694d35a940a3888ad2116c.
